repo_url: https://github.com/HEIG-VD-WEB/web-course
repo_name: HEIG-VD-WEB/web-course
site_name: HEIG-VD WEB 2023-2024
site_author: web-course contributors
site_url: https://heig-vd-web.github.io/web-course/
site_description: >-
  Course & tutorials about web technologies
copyright: Made with ❤, the DAI team, Bertil Chapuis, Olivier Lemer and Stefan Teofanovic
nav:
  - Home:
      - index.md
      - Week 1: weeks/week-1.md
      - Week 2: weeks/week-2.md
      - Week 3: weeks/week-3.md
      - Week 4: weeks/week-4.md
      - Week 5: weeks/week-5.md
      - Week 6: weeks/week-6.md
      - Week 7: weeks/week-7.md
      - Week 8: weeks/week-8.md
      - Week 9: weeks/week-9.md
      # - Week 10: weeks/week-10.md
      - Week 11: weeks/week-11/index.md
      - Week 12: weeks/week-12/index.md
      - Week 13: weeks/week-13.md
      - Week 14: weeks/week-14/index.md
      - Week 15: weeks/week-15/index.md
      - Week 16: weeks/week-16/index.md
  - Courses:
      - courses/index.md
      - Organisation: courses/organisation/index.md
      # - Introduction: courses/introduction/index.md
      - HTML: courses/html/index.md
      - CSS: courses/css/index.md
      - JavaScript: courses/javascript/index.md
      - Object-oriented JavaScript: courses/object-oriented-javascript/index.md
      - Document Object Model (DOM): courses/document-object-model/index.md
      - Canvas: courses/canvas/index.md
      - Web Server and PHP: courses/php-web-server/index.md
      - Node.js: courses/nodejs/index.md
      # - Dependencies: courses/dependencies/index.md
      # - PHP: courses/php/index.md
      # - PHP - linter: courses/php-linter/index.md
      # - PHP - ORM: courses/php-orm/index.md
      # - PHP - MVC: courses/php-mvc/index.md
      # - PHP - Routing: courses/php-routing/index.md
      # - PHP - Web framework: courses/php-web-framework/index.md
      # - PHP - Package manager: courses/php-package-manager/index.md
      # - Static Website generator: courses/static-website-generator/index.md
      # - Testing JavaScript application: courses/testing-javascript-applications/index.md
  - Tutorials:
      - tutorials/index.md
      - Generate and deploy a static website with Hugo and GitHub Actions: tutorials/generate-and-deploy-a-static-website-with-hugo-github-actions/index.md
      - Create a Hello World in PHP: tutorials/create-an-hello-world-in-php/index.md
      - Play with PHP basis: tutorials/play-with-php-basis/index.md
      - Create a To Do list in PHP: tutorials/create-a-todo-list-in-php/index.md
      - Create a simple CRUD in PHP: tutorials/create-a-simple-crud-in-php/index.md
      - Set a better Web server in php up: tutorials/set-a-better-web-server-in-php/index.md
  - Practical works:
      - practical-works/index.md
      - Practical Work 1: practical-works/practical-work-1/index.md
      - Practical Work 2: practical-works/practical-work-2/index.md
      - Practical Work 3: practical-works/practical-work-3/index.md
  - How-to guides:
      - how-to-guides/index.md
      - How to deploy on GitHub Pages: how-to-guides/how-to-deploy-on-github-pages/index.md
      - How to bind Windows folder with WSL and devcontainer (only on Windows): how-to-guides/how-to-bind-windows-folder-with-wsl-and-devcontainer/index.md
      - How to make a beautiful Website: how-to-guides/how-to-make-a-beatiful-website/index.md
  - Educational objectives:
      - educational-objectives/index.md
      - Part 1: educational-objectives/part-1/index.md
      - Part 2: educational-objectives/part-2/index.md
      - Part 3: educational-objectives/part-3/index.md
      # - Part 4: educational-objectives/part-4/index.md
  - Reference:
      - reference/index.md
      - About the calendar: reference/about-the-calendar.md
      - About the feedbacks: reference/about-the-feedbacks.md
      - About learning: reference/about-learning.md
      - About the course'evaluation: reference/about-evaluation-2023.md
      # - About the theory course: reference/about-the-theory-course.md
      # - About the code of conduct: reference/about-the-code-of-conduct.md

edit_uri: blob/main/docs/
theme:
  favicon: assets/images/favicon.svg
  language: en
  icon:
    logo: material/school
    repo: fontawesome/brands/git-alt
  name: material
  custom_dir: theme
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - toc.follow
plugins:
  - plantuml:
      puml_url: http://plantuml:8080
      puml_keyword: plantuml
  - glightbox
  - search
  - tags
reveal:
  path: reveal.js/dist
  transition: none # none/fade/slide/convex/concave/zoom
  theme:
    name: white.css
    path: theme
  plugin:
    path: reveal.js/plugin
extra:
  social:
    - icon: material/github
      link: https://github.com/HEIG-VD-WEB/web-course
      name: Web on Github
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - extra
  - footnotes
  - md_in_html
  - meta
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      dedent_subsections: true
      check_paths: true
      base_path: ["docs"]
      auto_append:
        - glossary.md
  - pymdownx.superfences:
      preserve_tabs: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables
  - toc:
      permalink: true
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
